id: I1D786A99
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T18:43:35+00:00'
last_modified: '2022-06-07T21:41:22.135317+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG12540
  title: གསང་སྔགས་རྙིང་མ་བའི་ཞལ་འདོན་ཕྱོགས་སྒྲིག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    AEC5:
      image_group_id: I1KG12572
      title: ''
      total_pages: 682
      order: 1
      base_file: AEC5.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
