id: P004285
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG12540
  title: གསང་སྔགས་རྙིང་མ་བའི་ཞལ་འདོན་ཕྱོགས་སྒྲིག
  author: ''
  volumes:
    468537a898e341a1be1d0ce1463fc455:
      image_group_id: I1KG12572
      title: ''
      volume_number: 1
      total_pages: 682
